### ISSUE TITLE
请问比赛的训练集和验证集现在还可以获取到吗？

### ISSUE THREAD

**Issue by wangwang110** [bitallin/MiduCTC-competition#3]
请问比赛的训练集和验证集现在还可以获取到吗？怎么获取呢？后面会不会有公开的可以持续提交的榜单呢？

**Comment by bitallin** [comment]
> 请问比赛的训练集和验证集现在还可以获取到吗？怎么获取呢？后面会不会有公开的可以持续提交的榜单呢？

你好，目前有公开[a榜数据集](https://aistudio.baidu.com/aistudio/datasetdetail/157348)
持续提交的榜单后面抽时间跟组委会商量再议哈。
